# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

.SILENT:clean
APP_NAME := test
ARDUINO_LIBS := AUnit
include /Users/luukmeier/Documents/Arduino/libraries/EpoxyDuino/EpoxyDuino.mk
