# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

.SILENT:clean
APP_NAME := test
ARDUINO_LIBS := AUnit
# EpoxyDuino.mk:
# 	wget https://raw.githubusercontent.com/bxparks/EpoxyDuino/develop/EpoxyDuino.mk
# 	touch $@ 
# include ./EpoxyDuino.mk
include /Users/luukmeier/Documents/Arduino/libraries/EpoxyDuino/EpoxyDuino.mk
